### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by timknut** [jalvz/depth-cover#3]
Hi!

Tried running:
`java -Xmx20G  -jar ~tikn/bioinf_tools/depth-cover-master/depth-cover.jar -bam RDCNORM000000202965.bam`

Got:
```Exception in thread "main" java.lang.NullPointerException
        at com.jalvz.bio.depthcover.input.ArgHandler.getOutDir(ArgHandler.java:67)
        at com.jalvz.bio.depthcover.EndPoint.main(EndPoint.java:39)
```

Running to get help text shows:
```
java -jar ~tikn/bioinf_tools/depth-cover-master/depth-cover.jar        
12:02:59 - USAGE: java -jar depth-cover.jar -bam input.bam [OPTIONS]

  *NOTE*: consider the memory and GC settings for the JVM, i.e.: java -XX:+UseParallelGC -Xmx2g -jar depth-cover.jar ...
  If during execution you see an error like 'java.lang.OutOfMemoryError' you'll need to increase the
  memory allocation with the -Xmx argument. The --ignore-index option can reduce the memory footprint.

OPTIONS:
  -bed FILE              Calculates the coverage in the intervals specified in the given bed FILE (default = all aligned genome)
  -fasta FILE            Excludes Ns from the total number of alignable positions in the reference fasta FILE
  -l LIMIT               Excludes from the output any depth of coverage higher than LIMIT
  -a , --all             Writes the coverage for each locus in a separated file
  -d DIRECTORY           Writes the output files to DIRECTORY (default = same as input BAM file)
  -n NAME                Uses NAME as the file name of the output (default = same as input BAM file)
  --ignore-index         Ignores BAM index if present (forces sequential read)
  -h , --help            Prints this help
```

It does not mention the `-bam` parameter.
Is this the bug?

Best, Tim

**Comment by jalvz** [comment]
Hi, Tim;

Sorry for that. Try to pass the full path of `RDCNORM000000202965.bam`. Does that solve the issue? If so, I'll try to make a fix.

Cheers

**Comment by timknut** [comment]
Hi!
Yes, it found the file.
Did stop, and give:
```
15:02:55 - Started.
15:02:55 - Index found.
15:03:19 - SAM validation error: ERROR: Record 1, Read name HWI-1KL157:146:C4VLYACXX:1:1315:14399:14959, MAPQ should be 0 for unmapped read.
15:03:20 - No Data to write - BAM file seems to be empty or coverage = 0
15:03:20 - Exiting.

```

**Comment by jalvz** [comment]
That has been reported before and I never manage to reproduce it. 
The `SAM validation error` line is interesting, tho. It comes from the underlying parsing library (Piccard), that apparently doesn't like the BAM file.

Some suggest `samtools` or `piccard-tools` to filter out unmapped reads or set mapping qualities to 0. 
Check this thread out: https://www.biostars.org/p/55830/

Hope that helps!

**Comment by jalvz** [comment]
Hey Tim, did you finally manage to make it work?

**Comment by timknut** [comment]
Hi! Sorry. Actually, I have not tried.
I found other ways in the meantime, as often happen. Used goleft from Brent P. 

Tim
